package M0.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Everything_Constraints extends BaseConstraintsDescriptor {
  public Everything_Constraints() {
    super(MetaAdapterFactory.getConcept(0xb544eef0f49a49edL, 0x8feadb0bb2944fc1L, 0x3307ddef000009fdL, "M0.structure.Everything"));
  }

}
