package MPlus.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Family;
  private ConceptPresentation props_Fs2Ps;
  private ConceptPresentation props_M2P;
  private ConceptPresentation props_M2PRef;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Family:
        if (props_Family == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Family = cpb.create();
        }
        return props_Family;
      case LanguageConceptSwitch.Fs2Ps:
        if (props_Fs2Ps == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Fs2Ps = cpb.create();
        }
        return props_Fs2Ps;
      case LanguageConceptSwitch.M2P:
        if (props_M2P == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_M2P = cpb.create();
        }
        return props_M2P;
      case LanguageConceptSwitch.M2PRef:
        if (props_M2PRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0xe90a707621864cb1L, 0x8bc8b8dac00b7356L, 0x551d94c4de67cL, 0x551d94c4de67dL, "m2p", "", "");
          props_M2PRef = cpb.create();
        }
        return props_M2PRef;
    }
    return null;
  }
}
