package personssolution.mypersons;

/*Generated by MPS */


public class Map_Persons {
  public static void main(String[] args) {
    System.out.println("asdf");
    System.out.println("larissa");
  }
}
