package families.solution;

/*Generated by MPS */


public class Map_Persons {
  public static void main(String[] args) {
    System.out.println("Asdfeinefamilie");
    System.out.println("Larissaeinefamilie");
  }
}
